// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wireguard.Dashboard.Data;

namespace Wireguard.Dashboard.Data.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200212120931_InitialWgDashboardDbMigration")]
    partial class InitialWgDashboardDbMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Wireguard.Dashboard.Models.Peer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("PreSharedKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("PrivateKey")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("VirtualIp")
                        .IsRequired()
                        .HasColumnType("binary(8)")
                        .IsFixedLength(true)
                        .HasMaxLength(16);

                    b.HasKey("Id");

                    b.ToTable("Peers");
                });

            modelBuilder.Entity("Wireguard.Dashboard.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte>("CIDR")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("EnableSecureDns")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NetworkAdapter")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<ushort?>("Port")
                        .HasColumnType("smallint unsigned");

                    b.Property<byte[]>("PublicIp")
                        .HasColumnType("binary(16)")
                        .IsFixedLength(true)
                        .HasMaxLength(16);

                    b.Property<byte[]>("SecureDnsAddress")
                        .HasColumnType("binary(16)")
                        .IsFixedLength(true)
                        .HasMaxLength(16);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte[]>("VirtualAddress")
                        .IsRequired()
                        .HasColumnType("binary(16)")
                        .IsFixedLength(true)
                        .HasMaxLength(16);

                    b.Property<string>("WireguardAdapterName")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Server");
                });
#pragma warning restore 612, 618
        }
    }
}
